language: python

env:
  - PHONOPY_VERSION=2.7.0
  - PHONOPY_VERSION=2.8.0

install:
  - python -mpip install phonopy==$PHONOPY_VERSION
  - python -mpip install pytest pytest-cov
  - python -mpip install codecov coverage
script: python -mpytest tests -ra --cov=./ --log-level=DEBUG
after_success:
  - codecov
